[tool.poetry]
name = "fastcli"
version = "1.3.0"
description = "fastcli"
authors = ["electrolyteJ <electrolytej@gmail.com>"]
license = "Apache2"
readme = "README.md"
packages = [{ include = "fast", from = "src" }]

[tool.poetry.dependencies]
python = "^3.9"
tqdm = "^4.65.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"



