[tool.poetry]
name = "padb"
version = "1.2.0"
description = "padb tools"
authors = ["electrolyteJ <electrolytej@gmail.com>"]
license = "Apache2"
readme = "README.md"
packages = [{ include = "padb", from = "src" }]


[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.2"
flashcli = { path = "../flashcli", develop = true }

[tool.poetry.scripts]
padb = 'padb:entry'